### ISSUE TITLE
Support `keyframe-selector-notation`

### ISSUE THREAD

**Issue by AlexWayfer** [alexrudd2/linter-stylelint#132]
Related to https://github.com/AtomLinter/linter-stylelint/issues/584, I believe, but another one.

![image](https://user-images.githubusercontent.com/6510020/191595496-7cff9bdc-4bb3-4829-bfba-7dc385693bb9.png)

https://stylelint.io/user-guide/rules/list/keyframe-selector-notation/

**Comment by alexrudd2** [comment]
I think this is working, probably as of e20a68f34fa9586b32717dc3e227db66a1ce11d1

<img width="483" alt="Screen Shot 2022-10-18 at 7 08 36 PM" src="https://user-images.githubusercontent.com/52292902/196567645-de02dc1c-edbc-4c9b-ad12-69a3c02d655a.png">
